services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_logs
      MYSQL_USER: users1234
      MYSQL_PASSWORD: User1234
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: